boramboram_hackaton/projbstagram/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register, name='register'),
]

boramboram_hackaton/projbstagram/photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView

from .views import *
from .models import Photo

app_name = 'photo'

urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>/',DetailView.as_view(model=Photo,template_name='photo/detail.html'), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
]

boramboram_hackaton/projbstagram/profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('profile/home/', views.profile_home, name="profile_home"),
    path('profile/blog/', views.profile_blog, name="profile_blog"),
    path('profile/comment/', views.profile_comment, name="profile_comment"),
]

boramboram_hackaton/projbstagram/projbstagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('shop/', include('shop.urls')),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boramboram_hackaton/projbstagram/shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
]

boramboram_hackaton/projbstagram/accounts/models.py
from django.db import models

# Create your models here.

boramboram_hackaton/projbstagram/photo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Photo(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_photos')

    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=[str(self.id)])

boramboram_hackaton/projbstagram/profiles/models.py
from django.db import models

# Create your models here.

boramboram_hackaton/projbstagram/shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    meta_description = models.TextField(blank=True)

    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_in_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    meta_description = models.TextField(blank=True)

    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()

    available_display = models.BooleanField('Display', default=True)
    available_order = models.BooleanField('Order', default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        index_together = [['id','slug']]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

boramboram_hackaton/projbstagram/accounts/forms.py
from django.contrib.auth.models import User
from django import forms

class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password2']

boramboram_hackaton/projbstagram/accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm
# Create your views here.
def register(request):
    if request.method == 'POST':
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user': new_user})
    else:
        user_form = RegisterForm()

    return render(request, 'registration/register.html', {'form': user_form})

boramboram_hackaton/projbstagram/photo/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Photo

@login_required
def photo_list(request):
    photos = Photo.objects.all()
    return render(request, 'photo/list.html', {'photos':photos})

class PhotoUploadView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['photo','text']
    template_name = 'photo/upload.html'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form':form})

class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'photo/delete.html'

class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['photo','text']
    template_name = 'photo/update.html'

boramboram_hackaton/projbstagram/profiles/views.py
from django.shortcuts import render

# Create your views here.
def profile_home(request):
    return render(request,'profile_home.html')

def profile_blog(request):
    return render(request, 'profile_blog.html')

def profile_comment(request):
    return render(request, 'profile_comment.html')

boramboram_hackaton/projbstagram/shop/views.py
from django.shortcuts import render, get_object_or_404
#from cart.forms import AddProductForm
from .models import *

def product_in_category(request, category_slug=None):
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available_display=True)

    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=current_category)

    return render(request, 'shop/list.html',
                  {'current_category': current_category, 'categories': categories, 'products': products})


def product_detail(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id, slug=product_slug)
    add_to_cart = AddProductForm(initial={'quantity':1})
    return render(request, 'shop/detail.html', {'product': product, 'add_to_cart':add_to_cart})

boramboram_hackaton/projbstagram/photo/templates/photo/delete.html
{% extends 'base.html' %}
{% block title %}- Delete{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <div class="alert alert-info">
            Do you want to delete {{object}}?
        </div>
        <form action="" method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Confirm">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

boramboram_hackaton/projbstagram/photo/templates/photo/detail.html
{% extends 'base.html' %}
{% block title %}
    {{object.text|truncatechars:10}}
{% endblock %}

{% block content %}
    <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <p><img src="{{object.photo.url}}" style="width:100%;"></p>
                <button type="button" class="btn btn-outline-primary btn-sm">
                    {{object.author.username}}</button>
                <p>{{object.text|linebreaksbr}}</p>

                <a href="{% url 'photo:photo_delete' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right">
                    Delete</a>
                <a href="{% url 'photo:photo_update' pk=object.id %}" class="btn btn-outline-success btn-sm float-right">
                    Update</a>
            </div>
            <div class="col-md-2"></div>
    </div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

boramboram_hackaton/projbstagram/photo/templates/photo/list.html
{% extends 'base.html' %}

{% block title %}- List{% endblock %}

{% block content %}
    {% for post in photos %}
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <p><img src="{{post.photo.url}}" style="width:100%;"></p>
                <button type="button" class="btn btn-xs btn-info">
                    {{post.author.username}}</button>
                <p>{{post.text|linebreaksbr}}</p>
                <p class="text-right">
                    <a href="{% url 'photo:photo_detail' pk=post.id %}" class="btn btn-xs btn-success">댓글달기</a>
                </p>
            </div>
            <div class="col-md-2"></div>
        </div>

    {% endfor %}
{% endblock %}

boramboram_hackaton/projbstagram/photo/templates/photo/update.html
{% extends 'base.html' %}
{% block title %}
- Upate
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <form action="" method="post" enctype="multipart/form-data">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Update">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

boramboram_hackaton/projbstagram/photo/templates/photo/upload.html
{% extends 'base.html' %}
{% block title %}
- Upload
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <form action="" method="post" enctype="multipart/form-data">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Upload">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

boramboram_hackaton/projbstagram/shop/templates/shop/detail.html
{% extends 'base.html' %}
{% block title %}Product Detail{% endblock %}
{% block content %}


        <div class="container">
            <div class="row">
                <div class="col-4">
                    <img src="{{product.image.url}}" width="100%">
                </div>
                <div class="col">
                    <h1 class="display-6">{{product.name}}</h1>

                    <p><span class="badge badge-secondary">Price</span> {{product.price}}</p>
                    <form action="{% url 'cart:product_add' product.id %}" method="post">
                        {{add_to_cart}}
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary btn-sm" value="Add to Cart">
                    </form>
                    <h5><span class="badge badge-secondary">Description</span>{{product.description|linebreaks}}</h5>
                </div>
            </div>

        </div>



{% endblock %}

boramboram_hackaton/projbstagram/shop/templates/shop/list.html
{% extends 'base.html' %}
{% block title %}Category Page{% endblock %}
{% block content %}


    <div class="row">
        <div class="col-2">
            <div class="list-group">
                <a href="/" class="list-group-item {% if not current_category %}active{% endif %}">All</a>
                {% for c in categories %}
                    <a href="{{c.get_absolute_url}}" class="list-group-item {% if current_category.slug == c.slug %}active{% endif %}">{{c.name}}</a>
                {% endfor %}
            </div>
        </div>


        <div class="col">
            <div class="alert alert-info" role="alert">
              {% if current_category %}{{current_category.name}}{% else %}All Products{% endif %}
            </div>
            <div class="row">
            {% for product in products %}

                <div class="col-4">
                    <div class="card">
                      <img class="card-img-top" src="{{product.image.url}}" alt="Product Image">
                      <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p class="card-text">{{product.description}} <span class="badge badge-secondary">${{product.price}}</span></p>
                        <a href="{{product.get_absolute_url}}" class="btn btn-primary">View Detail</a>
                      </div>
                    </div>
                </div>

            {% endfor %}
            </div>
        </div>
    </div>


{% endblock %}

boramboram_hackaton/projbstagram/templates/base.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>보람보람 {% block title %}{% endblock %}</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Hind:400,700" rel="stylesheet">
	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="css/bootstrap.min.css" />
	<!-- Slick -->
	<link type="text/css" rel="stylesheet" href="css/slick.css" />
	<link type="text/css" rel="stylesheet" href="css/slick-theme.css" />
	<!-- nouislider -->
	<link type="text/css" rel="stylesheet" href="css/nouislider.min.css" />
	<!-- Font Awesome Icon -->
	<link rel="stylesheet" href="css/font-awesome.min.css">
	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="css/style.css" />
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/nouislider.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/slick-theme.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

	<link rel="stylesheet" href="{% static 'fonts/FontAwesome.otf' %}">
	<link rel="stylesheet" href="{% static 'fonts/fontawesome-webfont.eot.eot' %}">
	<link rel="stylesheet" href="{% static 'fonts/fontawesome-webfont.ttf' %}">
	<link rel="stylesheet" href="{% static 'fonts/fontawesome-webfont.svg' %}">
	<link rel="stylesheet" href="{% static 'fonts/fontawesome-webfont.woff.woff' %}">
	<link rel="stylesheet" href="{% static 'fonts/fontawesome-webfont.woff2.woff2' %}">
	<link rel="stylesheet" href="{% static 'fonts/slick.eot.eot' %}">
	<link rel="stylesheet" href="{% static 'fonts/slick.svg' %}">
	<link rel="stylesheet" href="{% static 'fonts/slick.ttf' %}">
	<link rel="stylesheet" href="{% static 'fonts/slick.woff.woff' %}">
	<img src="{% static 'img/logo_.png' %}">

	<link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
	<link rel="stylesheet" href="{% static 'js/jquery.min.js' %}">
	<link rel="stylesheet" href="{% static 'js/jquery.zoom.min.js' %}">
	<link rel="stylesheet" href="{% static 'js/main.js' %}">
	<link rel="stylesheet" href="{% static 'js/nouislider.min.js' %}">
	<link rel="stylesheet" href="{% static 'js/slick.min.js' %}">
</head>

<body>
	<!-- HEADER -->
	<header>
		<!-- header -->
		<div id="header">
			<div class="container">
				<div class="pull-left">
					<!-- Logo -->
					<div class="header-logo">
						<a class="logo" href="#">
							<img src="./img/logo_.png" alt="">
						</a>
					</div>
					<!-- /Logo -->

					<!-- Search
					<div class="header-search">
						<form>
							<input class="input search-input" type="text" placeholder="Enter your keyword">
							<select class="input search-categories">
								<option value="0">All Categories</option>
								<option value="1"></option>
								<option value="1"></option>
							</select>
							<button class="search-btn"><i class="fa fa-search"></i></button>
						</form>
					</div>
					-->

				</div>
				<div class="pull-right">
					<ul class="header-btns">
						<!-- Account -->
						<li class="header-account dropdown default-dropdown">
							<div class="dropdown-toggle" role="button" aria-expanded="true">
								<div class="header-btns-icon">
									<i class="fa fa-user-o"></i>
								</div>
								<strong class="text-uppercase">My Account</strong>
							</div>
							{% if user.is_authenticated %}
							<a class="text-uppercase">{{user.get_username}}</a>
							<br>
							<a href="{% url 'logout' %}" class="text-uppercase">Logout</a> / <a href="{% url 'photo:photo_upload' %}" class="text-uppercase">file upload</a>
							{% else %}
							<a href="{% url 'login' %}" class="text-uppercase">Login</a> / <a href="{% url 'register' %}" class="text-uppercase">Join</a>
						    {% endif %}
						</li>
						<!-- /Account -->

						<!-- Mobile nav toggle-->
						<li class="nav-toggle">
							<button class="nav-toggle-btn main-btn icon-btn"><i class="fa fa-bars"></i></button>
						</li>
						<!-- / Mobile nav toggle -->
					</ul>
				</div>
			</div>
			<!-- header -->
		</div>
		<!-- container -->
	</header>
	<!-- /HEADER -->

	<!-- NAVIGATION -->
	<div id="navigation">
		<!-- container -->
		<div class="container">
			<div id="responsive-nav">
				<!-- category nav -->
				<div class="category-nav"> <!--show-on-click-->
					<span class="category-header">Categories</span>
					<ul class="category-list">
						<li><a href="#">일러스트</a></li>
						<li><a href="#">캐릭터 일러스트</a></li>
						<li><a href="#">라인드로잉</a></li>
						<li><a href="#">초상화</a></li>
						<li><a href="#">캘리그래피</a></li>
						<li><a href="#">웹툰/만화</a></li>
						<li><a href="#">영상</a></li>
						<li><a href="#">기타</a></li>
					</ul>
				</div>
				<!-- /category nav -->

				<!-- menu nav -->
				<div class="menu-nav">
					<span class="menu-header">Menu <i class="fa fa-bars"></i></span>
					<ul class="menu-list">
						<li><a href="{% url 'photo:photo_list' %}">Home</a></li>
						<li><a href="{% url 'shop:product_all' %}">Shop</a></li>
						<li><a href="{% url 'profile_home' %}">Designer</a></li>
					</ul>
				</div>
				<!-- menu nav -->
			</div>
		</div>
		<!-- /container -->
	</div>
	<!-- /NAVIGATION -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				{% block content %}
                {% endblock %}
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

	<!-- FOOTER -->
	<footer id="footer" class="section section-grey">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<!-- footer logo -->
					<div class="footer-logo">
						<a class="logo" href="#">
							<img src="./img/logo_.png" alt="">
						</a>
					</div>
					<!-- /footer logo -->
				</div>
			</div>
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<!-- footer info -->
					<div class="footer-info">
						Made by. Likelion 7th<br>
						@blogSoul @sryung1225 @Boraming @2kyung19
					</div>
					<!-- /footer info -->
				</div>
			</div>
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<!-- footer copyright -->
					<div class="footer-copyright">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</div>
					<!-- /footer copyright -->
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</footer>
	<!-- /FOOTER -->

	<!-- jQuery Plugins -->
	<script src="js/jquery.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/slick.min.js"></script>
	<script src="js/nouislider.min.js"></script>
	<script src="js/jquery.zoom.min.js"></script>
	<script src="js/main.js"></script>

</body>

</html>

boramboram_hackaton/projbstagram/templates/designer.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>보람보람</title>

    {% include 'include/main_head.html' %}
</head>

<body>
    {% include 'include/main_header_nav_fix.html' %}

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- section-title -->
				<div class="col-md-12">
					<div class="section-title">
						<h2 class="title">일러스트</h2>
						<div class="pull-right">
							<div class="product-slick-dots-1 custom-dots"></div>
						</div>
					</div>
				</div>
				<!-- /section-title -->

                <!-- banner -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="banner banner-2">
						<img src="/static/mo/img/banner14.jpg" alt="">
						<div class="banner-caption">
							<h2 class="white-color">일러스트</h2>
						</div>
					</div>
				</div>
				<!-- /banner -->

				<!-- Product Slick -->
				<div class="col-md-9 col-sm-6 col-xs-6">
					<div class="row">
						<div id="product-slick-1" class="product-slick">
							<!-- Product Single -->
							<div class="product product-single">
								<div class="product-thumb">
                                    <a href="/profile/home"><button class="main-btn quick-view"><i class="fa fa-search-plus"></i> profile</button></a>
									<img src="/static/mo/img/product01.jpg" alt="">
								</div>
								<div class="product-body">
									<h3 class="product-price"><b class="product-old-price">2kyung19</b></h3>
									<!-- <h2 class="product-name"><a href="#"></a></h2> -->
								</div>
							</div>
							<!-- /Product Single -->
						</div>
					</div>
				</div>
				<!-- /Product Slick -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->


	{% include 'include/main_footer.html' %}

    {% include 'include/main_scripts.html' %}

</body>

</html>

boramboram_hackaton/projbstagram/templates/product.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>모그리면돼?</title>

    <style>
        .add-to-heart {
          margin: 0px 10px;
          border-radius:10px;
          width: 95%;
          border: 2px solid #9114fc;
          background-color: #FFF;
          color: #9114fc;
        }

        .add-to-choice {
          margin: 0px 10px;
          border-radius:10px;
          width: 95%;
          height: 60px;
        }
    </style>
	{% include 'include/main_head.html' %}
</head>

<body>
	{% include 'include/main_header_nav_fix.html' %}

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!--  Product Details -->
				<div class="product product-details clearfix">
					<div class="col-md-6">
						<div id="product-main-view">
							<div class="product-view">
								<img src="/static/mo/img/main-product01.jpg" alt="">
							</div>
						</div>
					</div>
					<div class="col-md-6">
						<div class="product-body">
							<br>
							<div class="product-label">
								<span>캐릭터 일러스트</span>
							</div>
							<h2 class="product-name">남녀 누워있는 모습 그려주세요ㅜㅜ</h2>
							<br><br>
							<h4><strong>상세 설명</strong></h4>
							<p>남자는 베개를 베고 침대에 누워있고 그 위로 여자가 있어요..<br>
								둘이 서로를 쳐다보고 있고 입술이 닿을 듯한 모습을 연출하고 싶어요!<br>
								남자의 왼쪽 손이 여자의 머리를 감싸듯이 하면 좋을 것 같아요<br>
								***여자 단발머리*** 중요합니다! 잘 부탁드려요ㅜㅜㅜ
							</p>
							<br>
							<div class="product-btns">
								<button class="primary-btn add-to-heart"><i class="fa fa-heart"></i> &nbsp;&nbsp; 찜하기 </button>
								<p></p>
								<button class="primary-btn add-to-choice"><i class="fa fa-check"></i> &nbsp;&nbsp; 참여하기 </button>
							</div>
						</div>
					</div>
				</div>
				<!-- /Product Details -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->


	{% include 'include/main_footer.html' %}
	{% include 'include/main_scripts.html' %}
</body>

</html>